before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/gh-milestone/
archives:
  - name_template: '{{ .Os }}-{{ .Arch }}'
    format: binary
changelog:
  skip: true
